[
    {
        message: "1",
        name: "2",
        stack: "3",
        config: "4",
        code: "5",
        status: 404,
    },
    "Request failed with status code 404",
    "AxiosError",
    "AxiosError: Request failed with status code 404\n    at settle (D:\\workspace\\bot_test\\node_modules\\axios\\lib\\core\\settle.js:19:12)\n    at Unzip.handleStreamEnd (D:\\workspace\\bot_test\\node_modules\\axios\\lib\\adapters\\http.js:599:11)\n    at Unzip.emit (node:events:526:35)\n    at Unzip.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (D:\\workspace\\bot_test\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getWithCookies (D:\\workspace\\bot_test\\helpers\\api.ts:57:22)\n    at async getAvailibleDays (D:\\workspace\\bot_test\\helpers\\api.ts:201:26)\n    at async Task._execution (D:\\workspace\\bot_test\\TutorialBot.ts:57:46)",
    {
        transitional: "6",
        adapter: "7",
        transformRequest: "8",
        transformResponse: "9",
        timeout: 10000,
        xsrfCookieName: "10",
        xsrfHeaderName: "11",
        maxContentLength: -1,
        maxBodyLength: -1,
        env: "12",
        headers: "13",
        httpsAgent: "14",
        Accept: "15",
        "accept-encoding": "16",
        "accept-language": "17",
        Connection: "18",
        Host: "19",
        "if-none-match": "20",
        Referer: "21",
        "sec-fetch-dest": "22",
        "sec-fetch-mode": "23",
        "sec-fetch-site": "24",
        "user-agent": "25",
        "x-csrf-token": "26",
        "x-requested-with": "27",
        "sec-ch-ua": "28",
        "sec-ch-ua-mobile": "29",
        "sec-ch-ua-platform": "30",
        Cookie: "31",
        method: "32",
        url: "33",
    },
    "ERR_BAD_REQUEST",
    {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false,
    },
    ["34", "35", "36"],
    [null],
    [null],
    "XSRF-TOKEN",
    "X-XSRF-TOKEN",
    {},
    { Accept: "37", "User-Agent": "38", "Accept-Encoding": "39" },
    {
        _events: "40",
        _eventsCount: 2,
        options: "41",
        requests: "42",
        sockets: "43",
        freeSockets: "44",
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: "45",
        maxTotalSockets: null,
        totalSocketCount: 0,
        proxy: "46",
        proxyHeaders: "47",
        connectOpts: "48",
    },
    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "gzip, deflate, br, zstd",
    "en-US,en;q=0.9",
    "keep-alive",
    "ais.usvisa-info.com",
    'W/"d3d10dcacb37046ed590b12345dd5d65"',
    "https://ais.usvisa-info.com/en-am/niv/schedule/63415770/appointment",
    "empty",
    "navigate",
    "same-origin",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "R+d47K4ErrVuzyRwPYZD8GA3wnu8epVDbU3xPU4HGtufFudPOJsVdGhWA4qAW9S3GgNKWV6em1UfRlek8OSjig==",
    "XMLHttpRequest",
    '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
    "?0",
    '"Windows"',
    "_yatri_session=yzrGZ6uUJbRkUGjo3t%2B9GcNcTbrqWK9RHolyA9UsxC3PB72WiEqnFCfRIcYCUbQX1DfCbfXHG%2F1wiOKiPAcSy23JWdHoqH9mO2n69lw6HVDPLsvSu%2BNAnX5jqldeSUpudjlg1YDDAjQIWLI3sc%2FByKEnrCp3hQvL1inydySlP%2FVv5fMp2FZSZyR5qvcZW6QtKdGPi6tqEKMMnw0en8Z%2B7iiO1Qi39XK17F1e%2BmKQKthBL3zIXTkVPvcvAn9%2Be2A8gg1HIsDYwKeI2aLeKc%2B6cAxsCm%2FwfSi74kVxPQ3mjezprjInPOWPOMiNkq27AEfFJPM%3D--9VSrBlpv3GtslLGw--JjPKy4E9dylndK6kW8Q2ZA%3D%3D",
    "get",
    "https://ais.usvisa-info.com/en-am/niv/schedule/63415770/appointment/days/122.json",
    "xhr",
    "http",
    "fetch",
    "application/json, text/plain, */*",
    "axios/1.7.8",
    "gzip, compress, deflate, br",
    {},
    {},
    {},
    {},
    {},
    "lifo",
    "http://156.228.110.37:3128/",
    {},
    { ALPNProtocols: "49", host: "50", port: 3128 },
    ["51"],
    "156.228.110.37",
    "http/1.1",
];
